name: Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Java update
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

    #   - name: Install Flutter
    #     uses: subosito/flutter-action@v2
    #     with:
    #       flutter-version: "3.27.1"
    #       cache: true

    #   - name: Build APK
    #     run: |
    #         cd frontend
    #         flutter build apk --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up environment for Firebase
        run: |
          echo "${{ secrets.CREDENTIAL_FILE_CONTENT }}" > $HOME/service-account.json
          echo "File created at : $HOME/service-account.json"
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/service-account.json"
          echo $GOOGLE_APPLICATION_CREDENTIALS
          
      - name: Verify file
        run: |
          firebase projects:list

    #   - name: upload artifact to Firebase App Distribution
    #     uses: wzieba/Firebase-Distribution-Github-Action@v1
    #     with:
    #       appId: ${{secrets.FIREBASE_APP_ID}}
    #       serviceCredentialsFile: $HOME/service-account.json
    #       groups: tester
    #       file: build/app/outputs/flutter-apk/app-release.apk
